name: fluttermoji
description: A light-weight and highly customizable SVG graphic set for Flutter
  which generates avatars and provides a Customizer Widget, personalized
  CircleAvatar and other utility functions.
version: 1.0.0
# author: Suraj Kumar
homepage: https://github.com/psk907/fluttermoji

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  get: ^4.5.1
  shared_preferences: ^2.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - attributeicons/
